#!/usr/bin/env python3
"""
emit_app_data.py

Pure-stdlib pipeline step (no third-party deps) that reads the raw sourced
dataset at data/board_game_cafes.json and emits a typed, statically-importable
TypeScript bundle at src/data/board-game-cafes-bundle.ts.

This follows the canonical Kinetic Gain directory-build pipeline pattern:
    data/*.json  -->  pipeline/emit_app_data.py  -->  src/data/*-bundle.ts

Run from the repo root:
    python pipeline/emit_app_data.py

The output is plain, statically-typed data with no runtime logic, so the
Next.js app can `import { cafes } from "@/data/board-game-cafes-bundle"`
with zero API/DB calls at build or request time (output: 'export').

Scales to hundreds of rows without a rewrite: add cities by adding rows with
a new `city`/`state`, the slug/grouping logic below is fully generic.
"""

import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
INPUT_PATH = REPO_ROOT / "data" / "board_game_cafes.json"
OUTPUT_PATH = REPO_ROOT / "src" / "data" / "board-game-cafes-bundle.ts"

GENERATED_BANNER = (
    "// AUTO-GENERATED by pipeline/emit_app_data.py -- do not hand-edit.\n"
    "// Source of truth: data/board_game_cafes.json\n"
    "// Regenerate with: python pipeline/emit_app_data.py\n"
)


def slugify(value: str) -> str:
    """Lowercase, hyphen-delimited slug. No underscores, single hyphens only."""
    value = value.strip().lower()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    value = re.sub(r"-+", "-", value).strip("-")
    return value


def ts_string(value):
    """Emit a TS string literal, or the literal `null` for None."""
    if value is None:
        return "null"
    # json.dumps handles escaping quotes/backslashes correctly for a TS/JS string too.
    return json.dumps(value, ensure_ascii=False)


def load_cafes():
    if not INPUT_PATH.exists():
        print(f"ERROR: missing input file {INPUT_PATH}", file=sys.stderr)
        sys.exit(1)

    with INPUT_PATH.open("r", encoding="utf-8") as f:
        raw = json.load(f)

    cafes = raw.get("cafes", [])
    if not cafes:
        print("ERROR: data/board_game_cafes.json has no cafes[] entries", file=sys.stderr)
        sys.exit(1)

    required_fields = ["name", "city", "state", "address", "description", "sourceNote"]
    seen_ids = set()
    normalized = []

    for i, entry in enumerate(cafes):
        missing = [field for field in required_fields if not entry.get(field)]
        if missing:
            print(
                f"ERROR: cafe entry #{i} ({entry.get('name', '<unnamed>')}) "
                f"is missing required field(s): {missing}",
                file=sys.stderr,
            )
            sys.exit(1)

        city_slug = slugify(entry["city"])
        cafe_id = f"{city_slug}-{slugify(entry['name'])}"

        # Guard against silent duplicate slugs corrupting routing (fill-only
        # safety per the canonical pipeline doctrine -- fail loud, don't guess).
        if cafe_id in seen_ids:
            print(f"ERROR: duplicate slug '{cafe_id}' -- rename the source entry", file=sys.stderr)
            sys.exit(1)
        seen_ids.add(cafe_id)

        normalized.append(
            {
                "id": cafe_id,
                "slug": slugify(entry["name"]),
                "name": entry["name"],
                "city": entry["city"],
                "citySlug": city_slug,
                "state": entry["state"],
                "address": entry["address"],
                "description": entry["description"],
                "website": entry.get("website"),
                "sourceNote": entry["sourceNote"],
            }
        )

    # Stable order: city name, then cafe name -- keeps generated diffs small.
    normalized.sort(key=lambda c: (c["city"], c["name"]))
    return normalized


def emit_typescript(cafes) -> str:
    lines = [GENERATED_BANNER]
    lines.append("export interface BoardGameCafe {")
    lines.append("  id: string;")
    lines.append("  slug: string;")
    lines.append("  name: string;")
    lines.append("  city: string;")
    lines.append("  citySlug: string;")
    lines.append("  state: string;")
    lines.append("  address: string;")
    lines.append("  description: string;")
    lines.append("  website: string | null;")
    lines.append("  sourceNote: string;")
    lines.append("}")
    lines.append("")
    lines.append("export const boardGameCafes: BoardGameCafe[] = [")

    for cafe in cafes:
        lines.append("  {")
        lines.append(f"    id: {ts_string(cafe['id'])},")
        lines.append(f"    slug: {ts_string(cafe['slug'])},")
        lines.append(f"    name: {ts_string(cafe['name'])},")
        lines.append(f"    city: {ts_string(cafe['city'])},")
        lines.append(f"    citySlug: {ts_string(cafe['citySlug'])},")
        lines.append(f"    state: {ts_string(cafe['state'])},")
        lines.append(f"    address: {ts_string(cafe['address'])},")
        lines.append(f"    description: {ts_string(cafe['description'])},")
        lines.append(f"    website: {ts_string(cafe['website'])},")
        lines.append(f"    sourceNote: {ts_string(cafe['sourceNote'])},")
        lines.append("  },")

    lines.append("];")
    lines.append("")
    return "\n".join(lines)


def main():
    cafes = load_cafes()
    ts_content = emit_typescript(cafes)

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT_PATH.open("w", encoding="utf-8", newline="\n") as f:
        f.write(ts_content)

    cities = sorted(set(c["city"] for c in cafes))
    print(f"Wrote {len(cafes)} cafes across {len(cities)} cities to {OUTPUT_PATH}")
    for city in cities:
        count = sum(1 for c in cafes if c["city"] == city)
        print(f"  - {city}: {count}")


if __name__ == "__main__":
    main()
